# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9
pipelines:
  default:
    - step:
       script:
         - apt-get update && apt-get install -y libgconf-2-4 wget
         - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
         - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
         - apt-get update
         - apt-get install -y --no-install-recommends fonts-ipafont-gothic fonts-kacst fonts-thai-tlwg fonts-wqy-zenhei google-chrome-stable ttf-freefont
         - rm -rf /var/lib/apt/lists/*
         - apt-get purge --auto-remove -y curl
         - rm -rf /src/*.deb
         - groupadd -r pptruser
         - useradd -r -g pptruser -G audio,video pptruser
         - mkdir -p /home/pptruser/Downloads
         - chown -R pptruser:pptruser /home/pptruser
         - echo "-- Genesys WebComponents --"
         - node -v
         - npm -v
         - npm install
         - npm run build
         - npm run test
         - echo "Fanfare!"
